import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import authRoutes from './routes/auth';
import memberRoutes from './routes/members';
import statisticRoutes from './routes/statistics';
import partnerRoutes from './routes/partners';
import contentRoutes from './routes/content';
dotenv.config();
const app = express();
const PORT = process.env.PORT || 3001;
app.use(cors());
app.use(express.json());
app.use('/api/auth', authRoutes);
app.use('/api/members', memberRoutes);
app.use('/api/statistics', statisticRoutes);
app.use('/api/partners', partnerRoutes);
app.use('/api/content', contentRoutes);
app.get('/health', (req, res) => res.json({ status: 'ok' }));
app.listen(PORT, () => console.log('Server started'));
